name: CD - Publish Package

on:
  workflow_call:
    inputs:
      version:
        description: 'Versão do pacote a publicar'
        required: true
        type: string
    secrets:
      NPM_TOKEN:
        required: true
      GH_TOKEN:
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Autenticar no npmjs.org
      - name: Authenticate to npm registry
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      # Autenticar no GitHub Packages
      - name: Authenticate to GitHub Packages
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_TOKEN }}" >> ~/.npmrc

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npm run build --if-present

      - name: Bump version
        run: npm version ${{ inputs.version }} --no-git-tag-version

      - name: Publish to npm
        run: npm publish --access public

      - name: Publish to GitHub Packages
        run: npm publish --registry=https://npm.pkg.github.com
