name: deploy
on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
    secrets:
      NPM_TOKEN:
        required: true
      GH_TOKEN:
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Download NPM package artifacts
        uses: actions/download-artifact@v4
        with:
          name: npm-package
          path: ./build/npm-package

      - name: Setup Node.js and authenticate NPM
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          always-auth: true

      - name: Build package
        working-directory: ./build/npm-package
        run: npm run build --if-present

      - name: Publish to npm
        working-directory: ./build/npm-package
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Configure npm for GitHub Packages
        run: |
          echo "@${{ github.repository_owner }}:registry=https://npm.pkg.github.com" >> ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_TOKEN }}" >> ~/.npmrc

      - name: Publish to GitHub Packages
        working-directory: ./build/npm-package
        run: npm publish --registry=https://npm.pkg.github.com
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
