name: Release Pipeline


jobs:
  ci:
    uses: ./.github/workflows/CI.yml

  cd:
    needs: ci
    uses: ./.github/workflows/CD.yml
    with:
      version: ${{ github.sha }}
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
