name: Release Pipeline

on:
  push:
    branches:
      - master

jobs:
  ci:
    uses: ./.github/workflows/ci/ci.yml

  cd:
    needs: ci
    uses: ./.github/workflows/cd/cd.yml
    with:
      version: ${{ github.ref_name }}
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
