name: Release Pipeline

on:
  push:
    branches:
      - master

jobs:
  ci:
    uses: ./.github/workflows/CI.yml

  cd:
    needs: ci
    uses: ./.github/workflowsCD.yml
    with:
      version: ${{ github.sha }}
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
