name: Release Pipeline

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      PACKAGE_PATH: ./build/ExpForge.NpmPackage/package
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Install PowerShell
        run: sudo apt-get update && sudo apt-get install -y powershell

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Test
        run: dotnet test tests/ExpForge.Tests/ExpForge.Tests.csproj --configuration Debug

      - name: Publish NPM package artifacts
        if: github.event_name == 'push'
        run: dotnet publish -c Release -p:GenerateNpm=true

      - name: Upload NPM package artifacts
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: ${{ env.PACKAGE_PATH }} 

  deploy:
    if: github.event_name == 'push'
    needs: build-and-test
    uses: ./.github/workflows/deploy.yml
    with:
      version: ${{ github.sha }}
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
