name: Release Pipeline

on:
  push:
    branches:
      - master
  workflow_dispatch:  # Adiciona gatilho manual

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Test
        run: dotnet test tests/ExpForge.Tests/ExpForge.Tests.csproj --configuration Debug
      
      - name: Publish NPM package artifacts
        run: dotnet publish -c Release -p:GenerateNpm=true

      - name: Upload NPM package artifacts
        uses: actions/upload-artifact@v4
        with:
          name: npm-package
          path: ./build/npm-package
 
 
  deploy:
    if: github.event_name == 'workflow_dispatch'  # Executa deploy apenas manualmente
    needs: build-and-test
    uses: ./.github/workflows/deploy.yml
    with:
      version: ${{ github.sha }}
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
